create view VIEW_SUBJECTS as
  SELECT
         PREDMET.ID AS "ID",
         NAZEV,
         ZKRATKA,
         ROZSAH_HODIN,
         KATEGORIE_PREDMETU_ZKRATKA AS "KATEGORIE",
         ZAKONCENI_PREDMETU_ZKRATKA AS "ZPUSOB_ZAKONCENI",
         PRACOVNICI_ID AS "GARANT",
         DOPORUCENY_ROCNIK_CISLO_ROCNIKU AS "DOPORUCENY_ROCNIK",
         S.SEMESTR_ID AS "SEMESTR"
  FROM PREDMET LEFT JOIN SEM S on PREDMET.ID = S.PREDMET_ID
  /

